pipeline {
    agent any

    triggers {
        githubPush()
    }

    stages {
        stage('Build & Deploy') {
            when {
                branch 'BE'  // 이 브랜치에서만 실행됨
            }
            steps {
                sh 'docker compose down'
                sh 'docker compose up -d --build'
            }
        }
    }

    post {
        success {
            echo "✅ Build & deployment successful!"
        }
        failure {
            echo "❌ Build failed. Check logs."
        }
    }
}